### ISSUE TITLE
Deprecation warnings on Ember v1.13.0-beta.1

### ISSUE THREAD

**Issue by felixkiss** [aexmachina/ember-notify#54] opened 2015-05-21 15:20 UTC
We just upgraded our app to Ember v1.13.0-beta.1 and I am looking into all deprecation warnings.

I saw you already [tackled](https://github.com/aexmachina/ember-notify/commit/1b4c269708cf7f789949bbb0b4bcd629cf6703e2#diff-7562eb8eba3c3d86a671045f8c70107eL82) the deprecated [shared getter and setter methods](http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter) but had to [revert because of incompatibility with Ember <1.12](https://github.com/aexmachina/ember-notify/issues/52).

What are your plans on this? Will you release a new major version 4.0 where this is fixed or do we have to ignore the deprecation warnings for now?

**Comment by mjanda** [comment] 2015-05-25 08:53
Wouldn't this solve the problem? https://github.com/rwjblue/ember-new-computed

**Comment by aexmachina** [comment] 2015-05-25 12:20
Hi @felixkiss, thanks for the issue. There's a complex issue with a deprecation warning from `didInsertElement`, I've had a good look at it but unfortunately I'm flat out with other things right now.

@mjanda, yes that module will resolve the deprecation warnings from the old-style CP. I'd be happy to accept a PR if you're interested?

**Comment by wwwdata** [comment] 2015-07-01 11:07
I also still get a deprecation warning with ember 1.13


> DEPRECATION: Using `{{view}}` or any path based on it ('.../templates/components/ember-notify.hbs' @ L2:C2) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.

**Comment by shamanime** [comment] 2015-07-03 13:04
I also get the `Using {{view}}...` deprecation warning.

**Comment by joostdevries** [comment] 2015-07-12 15:39
+1

**Comment by tommyblue** [comment] 2015-07-15 17:23
+1

**Comment by joostdevries** [comment] 2015-07-16 07:47
Isn't this fixable by replacing the MessageView with a component?

**Comment by aexmachina** [comment] 2015-07-16 23:27
No, it's because it changes an attribute in didInsertElement.

**Comment by spruce** [comment] 2015-07-23 13:05
+1

**Comment by msalahz** [comment] 2015-07-27 11:51
+1

**Comment by aexmachina** [comment] 2015-07-27 12:00
I've started working in the next major version release with full ember 2.0
compatibility. How to have it finished in the next week or so.

**Comment by tommyblue** [comment] 2015-07-27 12:08
:+1:

**Comment by felixkiss** [comment] 2015-08-06 13:57
@aexmachina Any updates on your major version rewrite?

We want these deprecation warnings gone ;-)

**Comment by aexmachina** [comment] 2015-08-07 00:05
Yeah it's finished, just getting tests passing. I think the remaining
failures are actually an ember issue, will confirm tonight. Might have to
release a beta version with some rest failures to get it out the door.

**Comment by jcope2013** [comment] 2015-08-11 05:41
@aexmachina any update on status?

**Comment by aexmachina** [comment] 2015-08-11 13:27
I've pushed a new version to master which should resolve these issues. There's test failures on beta and canary, but I suspect that these are caused by unrelated issues. Can people please test using `ember-notify#master` and if we think it's good to go I'll publish v4.0. Please consult the CHANGELOG for upgrade instructions.

**Comment by byelipk** [comment] 2015-08-11 16:32
My app failed to launch when I tried the updated version on master branch. I receive the following error:

```
Cannot find module 'object-assign'
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/../path/to/my/app/node_modules/ember-notify/index.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I installed it with:

`npm install git+https://github.com/aexmachina/ember-notify.git --save-dev`

**Comment by aexmachina** [comment] 2015-08-12 01:48
Thanks, that's fixed now.

**Comment by jcope2013** [comment] 2015-08-12 05:58
ran into same issue as above on a fresh npm cache clean/npm install pointing at master with latest fix

**Comment by aexmachina** [comment] 2015-08-12 06:15
Yes, my mistake - should be fixed now via #61.

**Comment by felixkiss** [comment] 2015-08-12 13:49
It doesn't work for me.

Upgrade to master branch, `package.json`:
```
"ember-notify": "aexmachina/ember-notify#master",
```

I inject the notify service into a controller:
```
const { service } = Ember.inject;

export default Ember.Controller.extend({
  notify: service('notify'),
```

I use it:
```
self.notify.warning('Some message');
```

---

Error:
```
TypeError: self.notify.success is not a function
```

`self.notify` in the console:
```
> self.notify
InjectedProperty {type: "service", name: "notify", isDescriptor: true, _dependentKeys: undefined, _suspended: undefined…}
_cacheable: true
_dependentKeys: undefined
_getter: injectedPropertyGet(keyName)
_meta: undefined
_readOnly: false
_suspended: undefined
isDescriptor: true
name: "notify"
set: function AliasedProperty_oneWaySet(obj, keyName, value)
type: "service"
__proto__: Object
```

What can I do?

**Comment by aexmachina** [comment] 2015-08-12 23:20
You need to use `get` to access injected properties. Which reminds me, I need to update the docs

**Comment by msalahz** [comment] 2015-08-17 09:01
Any updates ?

**Comment by aexmachina** [comment] 2015-08-18 05:29
All the tests are passing on release, beta and canary so I've published v4.0.0. Let me know if there's any issues.

**Closed by aexmachina** 2015-08-18 05:29 UTC

**Comment by Panman8201** [comment] 2015-08-18 18:29
@aexmachina I'm not sure if you want to keep backwards compatibility, since it *is* a new major version, but you could include an initializer to inject it into routes and controllers like it used to be. That way ppl don't need to implicitly inject the service.

```javascript
// app/initializers/inject-notify-service.js
export function initialize( container, application ) {
  application.inject('route', 'notify', 'service:notify');
  application.inject('controller', 'notify', 'service:notify');
}

export default {
  name: 'inject-notify-service',
  initialize: initialize
};
```

**Comment by aexmachina** [comment] 2015-08-19 01:18
Yes I'm aware of that, although I think that it's clearer to have the dependency in the class. Also injecting `notify` caused a problem with liquid-fire. I'll add an optional initializer that you can manually import.

**Comment by aexmachina** [comment] 2015-08-19 03:53
I've added an initializer and docs to README.
