### ISSUE TITLE
Freeze!

### ISSUE THREAD

**Issue by lolmaus** [aexmachina/ember-notify#31] opened 2015-02-06 11:31 UTC
Hi!

Not sure whether the reason behind this is my incompetence or a problem in ember-notify.

Here's how i use it in my `application.hbs` template:

```
{{ ember-notify
  messageStyle='bootstrap'
  closeAfter=4000
}}
```

Here's how i use it in a component action:

```js
actions: {
  refresh: function() {
    Notify.alert('Bla bla');
  }
}
```

Here's how i call the action from the template:

```html
<button {{action "refresh"}}>Refresh</button>
```

When the promise is rejected, the ember-notify notification is displayed. After that, the tab freezes in Chrome with 100% CPU allocation.

If i comment out the `Notify.alert()`, the tab won't freeze.

**Comment by lolmaus** [comment] 2015-02-06 11:56
I've updated the top post with a reduced case.

**Comment by lolmaus** [comment] 2015-02-06 12:12
Here's Chrome CPU profile:

[![image](https://cloud.githubusercontent.com/assets/200884/6079081/c269c414-ae11-11e4-9999-146902bb9843.png)](https://cloud.githubusercontent.com/assets/200884/6079081/c269c414-ae11-11e4-9999-146902bb9843.png)


Looks like a recursion:

[![image](https://cloud.githubusercontent.com/assets/200884/6079150/71c500e0-ae12-11e4-904a-d6c110221ef8.png)](https://cloud.githubusercontent.com/assets/200884/6079150/71c500e0-ae12-11e4-904a-d6c110221ef8.png)

**Comment by aexmachina** [comment] 2015-02-12 02:18
Are you using Ember 1.10? I've just been made aware of an issue with HTMLBars that I haven't had a chance to fix yet.

**Comment by lolmaus** [comment] 2015-02-12 04:15
Nope, i'm still on 1.9.

**Comment by rudymalhi** [comment] 2015-02-23 11:06
I'm having a similar issue with Ember 1.10

**Comment by aexmachina** [comment] 2015-02-23 11:40
Is anyone able to share some code with me so I can try to fix the problem?
I can't currently reproduce the issue.

**Comment by aexmachina** [comment] 2015-05-18 06:55
Closing this issue as can't reproduce. Please reopen if necessary.

**Closed by aexmachina** 2015-05-18 06:55 UTC
